"""
Question Generator Service.

Generates realistic questions about a brand using LLM.
Simulates a real user searching for information about the brand.
"""

import os
import logging
from typing import List
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from tenacity import retry, stop_after_attempt, wait_exponential

logger = logging.getLogger(__name__)


class QuestionsResponse(BaseModel):
    """
    Structure for validating questions generated by the LLM.
    
    Ensures we always get a list of strings in the correct format.
    """
    questions: List[str] = Field(
        description="List of realistic questions about the brand that a typical user would ask",
        min_items=2,
        max_items=10
    )


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10)
)
def generate_questions(brand: str, num_questions: int = 2) -> List[str]:
    """
    Generate realistic questions about a brand using LLM.
    
    Simulates a real user searching for information about the brand.
    Uses structured output to guarantee the format.
    
    Args:
        brand: Name of the brand to generate questions about (e.g., "Nike", "Brevo")
        num_questions: Number of questions to generate (default: 2, will be used as guidance)
    
    Returns:
        List of questions (List[str])
    
    Raises:
        ValueError: If API key is missing
        Exception: If LLM call fails after retries
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY not found in environment variables")
    
    try:

        llm = ChatOpenAI(
            model="gpt-4o-mini",  
            temperature=0.7,  
            api_key=api_key
        )
        
        structured_llm = llm.with_structured_output(QuestionsResponse)
        
        prompt = f"""You are a real user searching for information about {brand}.

Generate {num_questions} realistic questions that a typical user would ask when researching this brand.
These questions should be:
- Natural and conversational (like real Google/Perplexity searches)
- Diverse (products, competitors, recommendations, reviews, pricing, availability)
- Specific to the brand and its industry
- Questions that users would actually type into search engines or AI assistants
- Include comparisons with competitors from the same industry

IMPORTANT: One and only one of the questions MUST be a comprehensive, exhaustive question about the brand's negative aspects, weaknesses, complaints, or criticisms. This question should be formulated to get a detailed, in-depth analysis of what users, customers, or experts say are the main problems, drawbacks, or negative points about {brand}. Make it natural and realistic, like a real user would ask when doing thorough research.

Brand: {brand}

Generate questions that sound like real user queries, not marketing questions.
Generate only the questions, ensuring they are realistic and varied."""
        
        response = structured_llm.invoke(prompt)
        
        questions = response.questions
        
        logger.info(f"Generated {len(questions)} questions for brand: {brand}")
        return questions
        
    except Exception as e:
        logger.error(f"Failed to generate questions for brand '{brand}': {str(e)}")
        raise
